---
--- Generated by Luanalysis
--- Created by 喜欢悠然独自在.
--- DateTime: 2024/3/26 20:27:52
---
-- 比较线程标识与锁中的标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    --释放锁 del key
    redis.call('del', KEYS[1])
end
return 0
